### ISSUE TITLE
Empty fields for specific tournaments

### ISSUE THREAD

**Issue by Tithanium** [RoyaleAPI/cr-api#242]
I request a list of tournement tags. Some of them are returned with missing fields. 
For example, the request :
```
GET
http://api.cr-api.com/tournaments/CV8UG9R
```
gave answer with many fields that are ok , but fields of interest such as 
members = []
and no field playerCount at all.
This occured on many tournaments (about 1/10 ?). The other tags provide answers with these fields properly filled...

## Issue Report:
 1.  recently, 
 2. Expected behaviour: provide the different fields as for the other tournements 
 3. 
same for tags (16/02/2018, 17:34 Paris) : 
['29PYPJJP', 'CU0PV0R', 'CP02QUL', 'C9VQQG0', 'CU0YYG2', 'CU0YRLV', '29P8VLLG', '29P8VCRJ', '20RRJ8R2', '20RQQVQ0', '20RJRJ0Y', '20RJRCPR', '20RJJQJV', '20RC0LGU']

A check of these tournaments show they are not empty.

Request some tournois tags and go through the list of data.. some are showing missing members fields and playerCounts

**Comment by fourjr** [comment]
Unsure if related, request for https://api.cr-api.com/tournaments/20GV8VGU returns https://hastebin.com/ticovodafe.json

Is the above response similar to what you got?

**Comment by Tithanium** [comment]
Yes it is : no data about the members, no field playerCount

**Comment by Tithanium** [comment]
In fact, the same pb appears on other data. Now, I have some cards in the decks that have their Id missing :(

**Comment by fourjr** [comment]
I retrieved that endpoint from `/tournaments/open `, the endpoint that I sent earlier seems to be functioning now, same for the one Tithanium sent.

**Comment by Gr8z** [comment]
I can confirm this bug, can reproduce it 90% of the time.

**Comment by fourjr** [comment]
I am unable to reproduce this bug anymore.
