### ISSUE TITLE
/profile/anyTag is not showing every request the same values for arena member

### ISSUE THREAD

**Issue by 1Tudor1** [RoyaleAPI/cr-api#243]
This should be at any request
![screenshot_68](https://user-images.githubusercontent.com/9017523/36323846-0080eeba-135b-11e8-822d-cd8141f2539c.png)

But I think it happens to be a bug
![screenshot_67](https://user-images.githubusercontent.com/9017523/36323836-f477e83a-135a-11e8-9d11-14f0fb0be772.png)

**Comment by fourjr** [comment]
What is the tag that gives you the limited data?

**Comment by 1Tudor1** [comment]
Mine for example: 
[http://api.cr-api.com/player/UJ2JCC9](url)
But i checked and i think for every tag it is the same.

**Comment by fourjr** [comment]
This is a weird bug.. It works sometimes and returns the limited data sometimes. No consistent way to reproduce.

**Comment by selfish** [comment]
Is this still happening?

**Comment by fourjr** [comment]
Unable to reproduce anymore.
