### ISSUE TITLE
querystring on popular/decks to specify battle or arena 

### ISSUE THREAD

**Issue by rex13164** [RoyaleAPI/cr-api#263]
it would be nice if http://api.cr-api.com/popular/decks could return values by battle type or arena.
monitoring top players is useful but their decks are not applicable to different levels of players

it could be a start to get the list of players ending in TV-royal that are already divided by arena

**Comment by selfish** [comment]
Great idea. Will be done. Sometime.

**Comment by yautah** [comment]
and also
how about add more filters and return more data in response ?

just like http://royaleapi.com/decks/popular?time=7d&sort=win&size=60&players=PvP&type=Ladder&& ?

it would be more useful

**Comment by selfish** [comment]
Since this isn't based on a database, and filtering the data is uber-tricky, I'm going to close this issue for now. Might revisit this in the future.
