### ISSUE TITLE
/player/8L9L9GL missing challengeType in "battles" element

### ISSUE THREAD

**Issue by mlieshoff** [RoyaleAPI/cr-api#267]
## Request Details:
```
GET
http://api.cr-api.com/player/8L9L9GL
```

## Response Details:
```
Code: 200

...,"battles":[{"type":"PvP","mode":{"...

```

## Issue Report:
I dont know if its relevant or not...

 1. Did you encounter this recently, or has this bug always been there?
It encounters only in the request for a single profile. In the multiple profiles, all battles elements have this value.
 2. Expected behaviour: set challengeType

**Comment by fourjr** [comment]
I just requested multiple profiles (https://api.cr-api.com/player/99LJJ0QQY,2P0LYQ?keys=battles) and I did not get `challengeType`.

Anyway, this might have been removed to solve #239 but ill let @selfish comment

**Comment by mlieshoff** [comment]
Please request without keys, regarding to my request.

**Comment by selfish** [comment]
ChallengeType only returns when the match was played in a challenge.
I'll make it return `null` instead of being missing when it's not relevant.
To be deployed in `v10.6.11`
