### ISSUE TITLE
Tournament search do not return startTime/endTime for an inProgress tournament

### ISSUE THREAD

**Issue by ChapiIL** [RoyaleAPI/cr-api#274]
## Request Details:

Tournament search should return start/end time for an in progress tournament.
using the tournaments endpoint do return the time correctly but the search doesn't.
```
GET
http://api.cr-api.com/tournaments/search?name=a
```

## Response Details:

```json
{
    "tag": "C9GLY0Q",
    "type": "passwordProtected",
    "status": "inProgress",
    "creatorTag": "#YGRY9G2V",
    "name": "free 2k open a b c d #84 lol H",
    "description": "Join telegram channel @crroyale786 for password fast fast",
    "maxCapacity": 1000,
    "preparationDuration": 7200,
    "duration": 3600,
    "createTime": 1520416253,
    "startTime": null,
    "endTime": null,
    "playerCount": 4,
    "members": []
}
```
Code: 200

[...]

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there?
 2. Expected behaviour: 
 3. Console logs (if applicable): 
 4. Screenshots (if applicable):

<!--
Some guidelines: 

If it’s a question (anything along the lines of “How do I … in Postman”), the answer might lie in our documentation - http://docs.cr-api.com

**Comment by fourjr** [comment]
Verified with `U0Q0L20` (just search a random letter in game to get a tag) 

For now, you can use `createTime` to figure out what are the values of the null data

**Comment by ChapiIL** [comment]
@fourjr 
> For now, you can use createTime to figure out what are the values of the null data
That is correct if the tour has not started before preparation time has finished.
If the creator starts the tournament before the preparation time has finished then you cannot rely on createTime

**Comment by ChapiIL** [comment]
In that case, how can we determine how much time left before the tournament ends?

**Comment by selfish** [comment]
This data is not available to me.
I'll stick in the calculated time, assuming in most cases it's correct.
Fixed in `v10.6.14`

**Comment by ChapiIL** [comment]
Thanks @selfish !
What happens in case the tournament starts before complete preparation time?
i.e. the user used "start now" before 2 preparation hours have completed.
Will the start/end times be updated?

**Comment by ChapiIL** [comment]
I've just stumbled into a tournament in which the endtime was not correct
I assume it's related to tournament start before preparation time has fully ended

**Comment by fourjr** [comment]
- Create a new issue, you can include a reference if you want 
- Add the full requested endpoint, a www.hastebin.com of the response and state your expected response.

**Comment by ChapiIL** [comment]
@fourjr I don't have the exact response anymore, I can only describe the issue

**Comment by fourjr** [comment]
State exact steps to reproduce then, if it isn't reproducible, it's most likely a one time thing. Report it when it happens again then

**Comment by fourjr** [comment]
Replying on a closed issue regarding a new bug report isn't going to helo fix the bug

**Comment by ChapiIL** [comment]
When I see the issue again I'll open a new issue. Thanks!

**Comment by ChapiIL** [comment]
I opened https://github.com/RoyaleAPI/cr-api/issues/291

**Comment by ChapiIL** [comment]
Seems like this bug returned 
And also other tournament APIs return start/end as None
