### ISSUE TITLE
Player endpoint returning invalid clan badge image URL's

### ISSUE THREAD

**Issue by PixelCrux** [RoyaleAPI/cr-api#279]
The URL's located in the player endpoint response at the locations like the ones listed below have recently become invalid.

- player/clan/badge/image
- player/battles/0/team/0/clan/badge/image

URL's are similar to:
https://cr-api.github.io/cr-api-assets/badges/Star_Shine_03.png

**Comment by selfish** [comment]
Fixed in `v10.6.8`
