### ISSUE TITLE
Documentation: Option to send multiple player tags in one request is unclear

### ISSUE THREAD

**Issue by mwolverine63** [RoyaleAPI/cr-api#285]
In the documentation, it states that you can list multiple player tags in one request.

However, it does not make it clear that this is treated as multiple requests at once -- I made the mistake of listing the top 200 player tags in this 'one' request, without realizing I was overloading the server.

**Comment by fourjr** [comment]
Understood. Will add a warning, note that it counts to your total request count as well.

@selfish, what about ratelimits and this?

**Comment by fourjr** [comment]
This issue was moved to RoyaleAPI/cr-api-docs#17
