### ISSUE TITLE
Different errors are returned as different types in different formats (See issue)

### ISSUE THREAD

**Issue by BlackHoleFox** [RoyaleAPI/cr-api#286]
So interesting thing ive run into. Getting a players name via tag
When its an unknown tag, it returns a 404 as just err
But when its a problem with its usage, such as an invalid tag or missing tag, it returns an object that has err.message
Is this intended and im doing something wrong or is it actually wonked?
Further testing shows when its an invalid tag, the 404 error is returned as `string`
But when the tag is missing, the error is returned as an `object`

**Comment by fourjr** [comment]
Can you send the tags you tested and the resposnes?

**Comment by BlackHoleFox** [comment]
Ignore the first part, its the command that invokes the API call. It is cut out of the string before the request. `!getplayer A` is the invalid one, and `!getplayer ` is the missing one.

**Comment by selfish** [comment]
I can't reproduce this. Please provide exact API calls, otherwise there's nothing I can do. Feel free to reopen the issue with more detail. Thanks
