### ISSUE TITLE
/endpoints as map with identifier as key

### ISSUE THREAD

**Issue by mlieshoff** [RoyaleAPI/cr-api#289]
## Request Details:
```
GET
http://api.royaleapi.com/endpoints
```

## Response Details:
[
  "/version",
  "/players?/:tag",
  "/players?/:tag/battles?",
  "/players?/:tag/chests?",
  "/clans?/search",
  "/clans?/tracking",
  "/clans?/:tag",
  "/clans?/:tag/battles?",
  "/clans?/:tag/history",
  "/clans?/:tag/history/weekly",
  "/clans?/:tag/tracking",
  "/clans?/:tag/track",
  "/tournaments?/open",
  "/tournaments?/known",
  "/tournaments?/search",
  "/tournaments?/:tag",
  "/top/clans?/:cc?",
  "/top/players?/:cc?",
  "/popular/clans?",
  "/popular/players?",
  "/popular/tournaments?",
  "/popular/decks?",
  "/auth/stats",
  "/constants?",
  "/endpoints"
]
```
Code: 200

[...]

```

## Issue Report:

Would be very cool, if we could have something like that:

[
  {
    "VERSION": ["/version"],
    "PLAYERS": ["/players?/:tag"],
    "PLAYERS_BATTLES": ["/players?/:tag/battles?"],
    "PLAYERS_CHESTS": ["/players?/:tag/chests?"],
    "CLANS_SEARCH": ["/clans?/search"],
    "CLANS_TRACKING": ["/clans?/tracking", "/clans?/:tag/tracking"],
    "CLANS": ["/clans?/:tag", "/clans?/:tag/track"],
    "CLANS_BATTLE": ["/clans?/:tag/battles?"],
    "CLANS_HISTORY": ["/clans?/:tag/history"],
    "CLANS_HISTORY_WEEKLY": ["/clans?/:tag/history/weekly"],
    "TOURNAMENTS_OPEN": ["/tournaments?/open"],
    "TOURNAMENTS_KNOWN": ["/tournaments?/known"],
    "TOURNAMENTS_SEARCH": ["/tournaments?/search"],
    "TOURNAMENTS": ["/tournaments?/:tag"],
    "TOP_CLANS": ["/top/clans?/:cc?"],
    "TOP_PLAYERS": ["/top/players?/:cc?"],
    "POPULAR_CLANS": ["/popular/clans?"],
    "POPULAR_PLAYERS": ["/popular/players?"],
    "POPULAR_TOURNAMENTS": ["/popular/tournaments?"],
    "POPULAR_DECKS": ["/popular/decks?"],
    "AUTH_STATS": ["/auth/stats"],
    "CONSTANTS": ["/constants?"],
    "ENDPOINTS": ["/endpoints"]
  }
]

Advantage of that: Wrappers could get the endpoints with a call to the API, instead of use of many hard-coded URL's.

**Comment by selfish** [comment]
Great idea, but this will require manual maintenance. Currently the list is dynamically created.
I'll try to come up with a solution.

**Comment by selfish** [comment]
I couldn't fond a solution that will not require manual maintenance from me. sorry..=\
