### ISSUE TITLE
Tournament endtime incorrect

### ISSUE THREAD

**Issue by ChapiIL** [RoyaleAPI/cr-api#291]
## Request Details:

```
GET
http://api.cr-api.com/tournaments/search?name=free
```

## Response Details:

For tournaments that are started manually before preparation time ends (using "start now") the endtime is not correct.
I had a case where i received a tournament in state inProgress and endtime for almost 2.5 hours from my request time, that is not possible.
```
Code: 200

[...]

```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there?
 2. Expected behaviour: 
 3. Console logs (if applicable): 
 4. Screenshots (if applicable):

**Comment by fourjr** [comment]
Do you check in-game or using the `/tournaments/:tag` endpoint?

**Comment by fourjr** [comment]
Verified with` U2GUP00` and `/tournaments/:tag`

DEPRECATION WARNING: cr-api.com is currently phased for removal. Please move over to royaleapi.com

**Comment by ChapiIL** [comment]
Sorry I used https://api.royaleapi.com/
I'm using the API and verifying the results in-game

**Comment by selfish** [comment]
Resolved by hiding end time when not confident.
Thank you.
