### ISSUE TITLE
Top players end point has null for clan chest crowns and donations delta

### ISSUE THREAD

**Issue by jimmyk3008** [RoyaleAPI/cr-api#293]
## Request Details:
```
GET
https://api.royaleapi.com/top/players
```

## Response Details:
```
Code: 200

[...other info here...]

+"name": "Suchteffekt"
    +"tag": "9PVUCC"
    +"rank": 200
    +"previousRank": 180
    +"expLevel": 13
    +"trophies": 6006
    +"clanChestCrowns": null
    +"donationsDelta": null
    +"clan": {#1084 …3}
    +"arena": {#1086 …4}

```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there? Only just started using this endpoint
 2. Expected behaviour: show clanChestCrowns and donationsDelta. Individual player profile shows:
```
+"donations": 222
    +"donationsReceived": 80
    +"donationsDelta": 142
```

**Comment by fourjr** [comment]
This might be due to the fact that looking at the  leaderboard doesn't give all those data, and hence you'd need another request for the additional information.

I'll leave this open for @selfish to comment

**Comment by selfish** [comment]
No longer relevant after clan wars. :)
