### ISSUE TITLE
/player/:tag/battles and ../chests to provide player name + tag 

### ISSUE THREAD

**Issue by fourjr** [RoyaleAPI/cr-api#297]
Include a "tag" in `/player/:tag/battles` and `/player/:tag/chests`, or if possible `name` as well and maybe some other metadata

**Comment by selfish** [comment]
This is super tricky, as it will require modifying the API in a significant way, especially for battles, where the result is an array.
I'll close this for now, and consider adding it in a later version.
If you have a concrete idea of how to achieve that without screwing up everything, LMK.

**Comment by fourjr** [comment]
This is more important for  chests compared to battles. For battles, we can look for a 1v1 battle and see who is in "team" and use that data but  there is no such data in chests
