### ISSUE TITLE
Clan Wars and other 2.2.1 features in API

### ISSUE THREAD

**Issue by GameDeve1oper** [RoyaleAPI/cr-api#303]
Hi, as you know, the clan chest was removed from the game, therefore, could you remove it from the api, and also add more information about players and clans? After all, they introduced clan wars and many other features.

**Comment by TheLearneer** [comment]
Cool down dude,
You need to give some time for the API devs to work on the changes.

Just give them some time. ;)

**Comment by selfish** [comment]
Exactly.
