### ISSUE TITLE
Unstable API

### ISSUE THREAD

**Issue by GameDeve1oper** [RoyaleAPI/cr-api#304]
Hello! Api has become quite unstable, errors appear that the tag is entered incorrectly, although it is entered correctly, sometimes data is not returned / or dolos are returned. Will it become stable and how soon will this happen?

**Comment by fourjr** [comment]
The API being unstable is due to an influx of developers using the API and the backend is unable to keep up. If you want better stability, you can [donate](https://royaleapi.com/donate)
