### ISSUE TITLE
Swagger description endpoint

### ISSUE THREAD

**Issue by mlieshoff** [RoyaleAPI/cr-api#315]
Could you please provide a swagger definition endpoint (or any other webservice description format).

**Comment by fourjr** [comment]
what do you mean by swagger..?

**Comment by selfish** [comment]
I'm willing to support it if there's an easy way to translate the current API to swagger.
And by easy I mean a JSON to Swagger javascript implementation.
I'm _not_ willing to manually maintain an additional schema.
Can you find anything as such?

**Comment by mlieshoff** [comment]
Sorry, for Python i didn't know, but i'll take a look on that, for Java there some tools to transform annotations to swagger definition.

**Comment by mlieshoff** [comment]
@fourjr i mean that: https://swagger.io

**Comment by amenadiel** [comment]
@selfish I see that the API response is served from express.js, so what library are you using to handle the API interactions?

Loopback provides a swagger endpoint by itself. JSON API should have a bridging library

**Comment by selfish** [comment]
Not all APIs use bridging. Loopback is great, but it's opinionated.
The cost, in time, of building with Loopback is often not worth it.

Since I'm not interested in investing time on that, I'm going to close the issue now.
If there's an out of the box free (time-wise) solution, feel free to reopen.
