### ISSUE TITLE
Receive "illegal characters" error for tag that has valid characters

### ISSUE THREAD

**Issue by ahdavis** [RoyaleAPI/cr-api#317]
## Request Details:
```
GET
http://api.royaleapi.com/clan/2LVYYGUU​
```

## Response Details:
```
Code: 400
Illegal characters in tag (allowed: 0289CGJLPQRUVY) | Additional information and support: http://discord.me/royaleapi
```

## Issue Report:
 The clan tag being requested contains all valid characters, but I get the error message above.
This performs the query correctly; https://royaleapi.com/clan/2LVYYGUU

**Comment by fourjr** [comment]
Somehow, my application works with this tag, but a direct request doesn't 🤔

**Comment by fourjr** [comment]
There is a zero width space after the last `U`

**Comment by ahdavis** [comment]
Thank you, and sorry about that.  I copied and pasted the tag from an email instead of typing it manually.
