### ISSUE TITLE
Cache issue for a specific clan - always returns too many requests

### ISSUE THREAD

**Issue by munsterlander** [RoyaleAPI/cr-api#320]
## Request Details:
```
GET
$url = 'https://api.royaleapi.com/clan/9JULYGJV';
$results = file_get_contents($url,true, $context);
```

## Response Details:
```
Warning: file_get_contents(https://api.royaleapi.com/clan/9JULYGJV): failed to open stream: HTTP request failed! HTTP/1.1 429 Too Many Requests in /storage/ssd5/197/5223197/public_html/bot2.php on line 67
array(17) { [0]=> string(30) "HTTP/1.1 429 Too Many Requests" [1]=> string(35) "Date: Mon, 14 May 2018 00:24:44 GMT" [2]=> string(45) "Content-Type: application/json; charset=utf-8" [3]=> string(19) "Content-Length: 125" [4]=> string(17) "Connection: close" [5]=> string(142) "Set-Cookie: __cfduid=d2e5b3c9861e83233f969d32a74797ade1526257484; expires=Tue, 14-May-19 00:24:44 GMT; path=/; domain=.royaleapi.com; HttpOnly" [6]=> string(30) "Access-Control-Allow-Origin: *" [7]=> string(21) "X-Powered-By: Express" [8]=> string(12) "Vary: Origin" [9]=> string(20) "X-Ratelimit-Limit: 3" [10]=> string(24) "X-Ratelimit-Remaining: 0" [11]=> string(32) "X-Ratelimit-Reset: 1526257483923" [12]=> string(40) "Etag: W/"7d-/6HiZOxPWEx+4j7jansqoHE5pWg"" [13]=> string(14) "Via: 1.1 vegur" [14]=> string(98) "Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"" [15]=> string(18) "Server: cloudflare" [16]=> string(28) "CF-RAY: 41a9393f1ca55eb2-TPA" }

```

## Issue Report:
This is a rate limited request.  It doesn't matter if this is the only request or in a series of requests.  For this specific clan, the server response will always be that there were too many requests.  All other requests work as expected.   Based on conversation with @selfish, suspect caching issue to blame.

**Comment by fourjr** [comment]
![image](https://user-images.githubusercontent.com/28086837/40000606-d9a3e97a-57be-11e8-80d9-4701fecd7c04.png)
I cannot reproduce this

**Comment by munsterlander** [comment]
I think this had to do with the API going down.  This issue https://github.com/RoyaleAPI/cr-api/issues/325 is very similar to what I was experiencing.

**Comment by munsterlander** [comment]
Also, is there an issue with the key then, because look at this:

![image](https://user-images.githubusercontent.com/17042581/40081257-51d168ae-5842-11e8-8c27-616143b072e2.png)

Immediately followed by:

![image](https://user-images.githubusercontent.com/17042581/40081282-62e38122-5842-11e8-928f-751ac3aefc54.png)


Immediately followed by:

![image](https://user-images.githubusercontent.com/17042581/40081307-730365e0-5842-11e8-9103-0140c4b50f94.png)

Please reopen this as there is definitely an issue.

**Comment by munsterlander** [comment]
I can run that request for that clan 100 times and it still fails, choose any other clan 100 times, no problem.  Is there an issue with the clan or my auth token for that clan?

**Comment by munsterlander** [comment]
Even tried a new token and it still fails from a different ip and just using Postman in Chrome to send the GET request.

**Comment by fourjr** [comment]
Is it only this specific clan tag?

**Comment by munsterlander** [comment]
@fourjr I cannot reopen the issue as you closed it.  I can only reopen issues I close.

https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github

**Comment by munsterlander** [comment]
Thanks!  That appears to have done it except everything is now returning application error, so I presume API is down at the moment.
