### ISSUE TITLE
Endpoints for Clan Wars stats

### ISSUE THREAD

**Issue by dreadklaxon** [RoyaleAPI/cr-api#322]
It would be great to have API access to the stats you can see on your Clan page on the Past Wars tab. You can see an example of this data in use at bit.ly/clanstats (see the Wars and Battles tabs).. right now it is all manual entry. Thanks!

**Comment by dreadklaxon** [comment]
This data is now available on statsroyale, which leads me to believe it is now public? Can this be revisited?

See e.g. https://statsroyale.com/clan/8JV9PJJ8/war/history

**Comment by fourjr** [comment]
Check /clan/:tag/warlog
