### ISSUE TITLE
x-ratelimit-reset is wrong

### ISSUE THREAD

**Issue by zut86** [RoyaleAPI/cr-api#325]
Hello and thanks for everything you do :)

My issue is simple, I have 

x-ratelimit-remaining =0

for 'https://api.royaleapi.com/clan/'+clanTag (where clanTag is the tag of my clan)

The x-ratelimit-reset is always giving me the current time of the request.

I hope I did not misundersand the way it works and not taking your time for nothing

**Comment by zut86** [comment]
sorry I should precise that I also do 

'https://api.royaleapi.com/player/'+tagList+"/chests"
and
'https://api.royaleapi.com/player/'+tagList

with success.

I run the /clan every minutes at 0 second  <--- this one is the problem with the remaining
The first /player every minutes at 10 seconds and the second on 2 seconds later.

**Comment by munsterlander** [comment]
I have the same issue for a certain clan.  Other clans, no issues at all.  They closed my issue but I hope to have it re-opened.  For what its worth, have you tried other clan tags?

**Comment by zut86** [comment]
no only mine

**Comment by munsterlander** [comment]
Try this clan and tell me what happens, if you don't mind:  9JULYGJV.  Send your tag and I will give it a go as well.

**Comment by zut86** [comment]
My tag clan is 8PL8CGU0

I just tried yours but I guess there is a global problem actually with requests. I will try later.

**Comment by selfish** [comment]
I cleared all cache today.
@zut86, @munsterlander - does the issue persist?

**Comment by munsterlander** [comment]
@selfish No, everything is good now.  I just checked his clan as well and it returns data now.  I think clearing the cache fixed all of these issues.

**Comment by zut86** [comment]
sorry I just saw your messages. I checked and everything is ok. Thanks again for what you did, you do and you'll do i'm sure ;)
