### ISSUE TITLE
Rate limit not reseting on player/chests for one TAG only

### ISSUE THREAD

**Issue by condemime** [RoyaleAPI/cr-api#329]
Rate limit remaining is stucked at 0.
This is only for the player chests endpoint, and for only one tag !
No problem on other endpoints, no problem for all the player of my clan, except just one.
I loop every 30 min with a 2 sec sleep between each requests, there is no reason to exceed the rate limit.

## Request Details:

GET
https://api.royaleapi.com/player/C8LC02YR/chests

## Response Details:
Status : 429
Rate limit exceeded
X-Ratelimit-Limit: 3
X-Ratelimit-Remaining: 0
X-Ratelimit-Reset: 1526587577580

## Issue Report:
 1. Since 2018-05-17 04:00:00
 2. Expected behaviour: the rate limit should be reseted at the unixtimestamp

**Comment by selfish** [comment]
Is this for any player or just this one?

**Comment by condemime** [comment]
hi, just this one.  I see that it was working this morning before the api went done.
