### ISSUE TITLE
Add utcWarStart of each started ClanWar to battles data (or wherever it fits).

### ISSUE THREAD

**Issue by gabebor** [RoyaleAPI/cr-api#332]
Currently https://api.royaleapi.com/clan/<TAG>/battles return just a collection of single fights.

Add **utcWarStart** of each started ClanWar to battles data like **clanWarCollectionDay**, **clanWarWarDay**, ...

With **utcWarStart** we can get the hole context of a war from clanWarCollectionDay(24hours) + clanWarWarDay(24hours)
Example for clanWarCollectionDay shown below:
```
{
    'type': 'clanWarCollectionDay',
    'challengeType': None,
	'mode': {
		'id': 72000060,
		'name': 'Overtime_Ladder'
	},
	'winCountBefore': None,
->	'utcWarStart':1525610914
	'utcTime': 1525614914,
	'deckType': 'slotDeck',
	'teamSize': 1,
	'winner': -1,
	'teamCrowns': 0,
	'opponentCrowns': 1,
	'team': [{
		'tag': '12345678',
		'name': 'JustAName',
		'crownsEarned': 0,
		'startTrophies': 3853,
		'clan': {},
		'deckLink': '...',
		'deck': []
	}],
	'opponent': [{
		'tag': '98CUQL2P',
		'name': 'tano',
		'crownsEarned': 1,
		'startTrophies': 3914,
		'clan': {},
		'deckLink': '...',
		'deck': []
	}],
	'arena': {}
}
```

**Comment by fourjr** [comment]
If you don’t see a specific feature, it is most likely because they aren’t able to get those data, or they are limited by Supercell guidelines on what we can show you publicly.

These new API endpoints might fit your need:
```
Current War:
    /clans?/:tag/war
Past Wars Log:
    /clans?/:tag/warlog
```

**Comment by gabebor** [comment]
sounds good, looks like give me a context to each war :)
when will this be available? (aprox)
