### ISSUE TITLE
⛵️War Data TDL

### ISSUE THREAD

**Issue by selfish** [RoyaleAPI/cr-api#333]
|Feature   |Status |
|:---|:---
**=== Features expected in the future ===** | 
Unique identifier / time. | Completed
Number of cards earned (@bpruf) | Completed
Add war log in clan history (#345) | To do
Leaderboard for clan wars | To do
Collection day total battles/wins | To do
War state instead of clanChest state in /clan/:tag (#355) | Expected in the future
Clan members not in war (@watermeloen)  | Optional. Might do
|  |
**=== Features Seeking a way to create ===** |
Clan war trophies in clan endpoint | Data currently inaccessible
Available Battle count (#334) | Data currently inaccessible
Cards earned  | Data currently inaccessible
War day total battles available (@janxin) | Data currently inaccessible
|  |
**=== Features in discussion or ruled out ===** |
Provide `clan` data when there is state is `notInWar` (@fourjr) | Why?
`season` key in /warlog to fetch battles from another season (10 war limit) (@janxin)  | Data older than last 10 wars not avilable in API

**Comment by bpruf** [comment]
also can you add 'cards earned' to clan battles?

**Comment by janxin** [comment]
This is something we really need so I'd like to propose to add some additional information if it is possibile, in particular to warlog.

1. War date start/end.
2. Collection day number of battles and number of victories. Actually only cards earned value is provided.
3. The max trophies for both players. This is an important information for both clan leader and player to undestand the theoretical match difficulty.
4. Number of friendly battles played using the war cards. This is an important value for a clan leader to understand how a player tries the deck before the attack.
5. The cards used by each player and the card level to let the leader know if he choose too low levelled cards. Here only the card reference and the level is significant.

**Comment by janxin** [comment]
When a player gets two battles, there's no way to know if he/she played both of them In warlog response

**Comment by gabebor** [comment]
-> Minimum, we still need collectionDay start timestamp:
Remember each of collectionDay, warDay are excactly 24h so we can calculate.

->Nice would be Start and End timestamp for each collectionDay, warDay
This would help to reconnect shortly before ending the current collectionDay, warDay to see wich clan member did his job. 

->Best would be to add those information into each war of the warlogs endpoint too.

Currently i'am forced to let it run all the time and hope to not miss the change from collectionDay to warDay or if a new collectionDay  starts.

**Comment by stekylsha** [comment]
I second @janxin request for start and end time.  I would like to see this so the data from `/battles/.../type=war` can be aggregated with the data from `/warlog`.

**Comment by janxin** [comment]
warlog actually returns last 10 wars but it would be better to add a season key to fetch the warlog data for the required season, so we can have all war log data for each clan, next a last key should be provided to fetch only the last ended war. If any key is provided, it works as it works now.

**Comment by fourjr** [comment]
@janxin Regarding your first reply:
```
3. The max trophies for both players. This is an important information for both clan leader and player to undestand the theoretical match difficulty.
4. Number of friendly battles played using the war cards. This is an important value for a clan leader to understand how a player tries the deck before the attack.
5. The cards used by each player and the card level to let the leader know if he choose too low levelled cards. Here only the card reference and the level is significant.
```
3. Do you mean personal best? This info isn't really directly related to clan wars and even battles info aren't given in /war or /warlog
4. Could you check if war deck friendly battles have a special `mode`? This will probably only be available in /player/:tag/battles or /clan/:tag battles
5. I assume you mean the deck used in war battle, refer to point 3

**Comment by janxin** [comment]
@fourjr 
3. Yes. It is not related to clan war but if I need that information I have to query the server again.
4. No it is ClanMate
5. Yes.

**Comment by selfish** [comment]
Ping to mention this issue isn't forgotten.
Still trying to reach the relevant data.

**Comment by dfomin** [comment]
Hello. You mention that warlog return only last 10 battles from supercell server but I see that data for older clan wars is available on your server (I suppose it's stored locally). I can get HTML representation of a lot of clan wars by [url](https://royaleapi.com/inc/player/cw_history?player_tag=8RQVRJUC). Why it can't be available through API? Thanks.

**Comment by fourjr** [comment]
That's done using a database to save all the war logs. You can do the same on your application.
