### ISSUE TITLE
Clan wars additiona data

### ISSUE THREAD

**Issue by janxin** [RoyaleAPI/cr-api#335]
Hello,
I just noticed you provide clan wars information and that's a really great thing. I'd like to propose to add some additional information if it is possibile, in particular to warlog.

1. War date start/end
2. Collection day number of battles and number of victories. Actually only cards earned value is provided.
3. The max trophies for both players. This is an important information for both clan leader and player to undestand the theoretical match difficulty.
4. Number of friendly battles played using the war cards. This is an important value for a clan leader to understand how a player tries the deck before the attack.
5. The cards used by each player and the card level to let the leader know if he choose too low levelled cards. Here only the card reference and the level is significant.

Thank you and keeu up the great work

**Comment by fourjr** [comment]
Please comment on #333
