### ISSUE TITLE
`https://api.royaleapi.com/clan/:tag/battles?type=war` returns more than just war battles

### ISSUE THREAD

**Issue by stekylsha** [RoyaleAPI/cr-api#339]
## Request Details:
```
curl -X GET -H "Authorization: Bearer $( cat ~/.crapi.key )" "https://api.royaleapi.com/clan/${TAG}/battles?type=war&max=2" | python -m json.tool
```
## Response Details:
```
...
        "mode": {
            "cardLevels": "Friendly",
            "deck": "Draft",
            "name": "TeamVsTeam_Touchdown_Draft",
...
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there?
Recently.  This seems to have happened with the last release as it was working as expected before.
 2. Expected behaviour:
Only battles of type `clanWarCollectionDay` and `clanWarWarDay`
 3. Console logs (if applicable): 
N/A
 4. Screenshots (if applicable):
N/A

**Comment by fourjr** [comment]
What is the clan `TAG` used here?

**Comment by stekylsha** [comment]
This is happening for both `8PGGUR88` and `YVV9PR`.
```
    {
        "arena": {
            ...
        },
        "challengeType": "unknown:73001394",
        "deckType": "draft",
        "mode": {
            "cardLevels": "Friendly",
            "deck": "Draft",
            "name": "CardReleaseDraft",
            "overtimeSeconds": 180,
            "players": "PvP",
            "sameDeck": false
        },
...
        "teamCrowns": 0,
        "teamSize": 1,
        "type": "challenge",
        "utcTime": 1526045279,
        "winCountBefore": null,
        "winner": -1
    },
```
Important part of that is `"type": "challenge",`.  This is happening for both clan tags.  The same curl was working previously.

**Comment by olemartin** [comment]
Same with type=clanMate, get all type of matches

**Comment by stekylsha** [comment]
@janxin, I was going to create another issue for the missing data after I verified it was happening and steps to reproduce.  I don't know for sure, but I don't think it should be part of this issue.
