### ISSUE TITLE
Pagination not working on /player/:tag/battles

### ISSUE THREAD

**Issue by BlackHoleFox** [RoyaleAPI/cr-api#342]
Request 1: `https://api.royaleapi.com/player/9YU92J0VC/battles` -> Line count of 13,703
Request 2: `https://api.royaleapi.com/player/9YU92J0VC/battles?max=5` -> Line count of 13,703

Expected result: Only 5 battles are returned and the JSON response is significantly smaller.

Actual result: Both JSON responses are the exact same, even ending with the same battle. 

Edit from fourjr: Both requests have the same amount of battles returned (25)

**Comment by fourjr** [comment]
Note: Pagination works as intended on /clan/:tag/battles

**Comment by selfish** [comment]
Fixed. Thanks
This was related to #356
