### ISSUE TITLE
GET https://api.royaleapi.com/clan/<TAG>/battles?type=war returns all battle types

### ISSUE THREAD

**Issue by jykntr** [RoyaleAPI/cr-api#344]
## Request Details:

```
GET https://api.royaleapi.com/clan/<TAG>/battles?type=war
```

## Response Details:

```
Code: 200
[
    {
        "type": "PvP",
        ...
    {
        "type": "clanWarCollectionDay",
        ...
    }
    {
        "type": "2v2",
        ...
    }
    {
        "type": "clanWarWarDay",
        ...
    }
    ...
]
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there?

I first saw this starting on 5/25, and has continued since.  It could have actually started a day or so earlier.

 2. Expected behaviour: 

Filter battle types so that they only include `clanWarCollectionDay` and `clanWarWarDay` types.

 3. Console logs (if applicable): 
 4. Screenshots (if applicable):

**Comment by fourjr** [comment]
#339
