### ISSUE TITLE
warlog endpoint, createdDate property seems to be wrong

### ISSUE THREAD

**Issue by mavinfinity** [RoyaleAPI/cr-api#349]
Calling https://api.royaleapi.com/clan/<TAG\>/warlog
The returned date in createdDate property seems to be wrong, because in the first war in the log (the last in time) the createdDate is not at least 2 days ago.

It seems to be the end date of the war (war endpoint manages "warEndTime or collectionEndTime") or the createdDate of the current war.

Edit: After some more testing createdDate property seems to be the end date of the war, not the start date

**Comment by gabebor** [comment]
jepp createdDate seems to be the wrong name... interpreted as endDate the received data make sence.
{'tag': '2V22909Q', 'name': 'bobbelsche', 'cardsEarned': 800, 'battlesPlayed': 1, 'wins': 0, 'seasonNumber': 4, 'createdDate': datetime.datetime(2018, 5, 31, 12, 56, 43)}
above are the newest (first) return of 'my' warlog from warlogs which is similar to the data if i click in cr directly. this was the my last fight in season 4 and season 5 has started.
now i understood, that all data from the "war" endpoint are fights of seasonNumber=5 which will come later into "warlogs".
i think

**Comment by selfish** [comment]
Thanks for the report.
This is the property name in the game data.
I'm going to leave it as it is for consistency.
This is only intended as a unique identifier for wars.
