### ISSUE TITLE
Remove developer key

### ISSUE THREAD

**Issue by sadeg1377** [RoyaleAPI/cr-api#350]
Remove developer key
Hi I have two developer key and both of them work but I want to remove one of them
I want to remove this one 
## Developer Key:

```
eyJhbGc...hhgAlCYI
```

in discord:
username: sadegh1377#0951
email: s.rezayifar@gmail.com

**Comment by selfish** [comment]
1. As we spoke, onve the switch from V2 to V3 keys is complete, all old keys will die.
2. Never expose your key. If you take a rate-limit hit because of that being here, you'll have to suffer it until the key is blocked. I have edited your message to hide the key.
