### ISSUE TITLE
Failing to request older battles

### ISSUE THREAD

**Issue by gahbriel** [RoyaleAPI/cr-api#351]
Hi

Thanks for the awesome work, cr-api team!

Id like to get ALL my battles, but I always get the last 25.

Im using this code https://api.royaleapi.com/player/9R2PRPJVG/battles. Ive tried adding parameters like page or timestamp without success though.

Any idea on what Im not doing right?

Thanks!

Best

**Comment by ZeNeLLiE** [comment]
The api can only retrieve last 25. You have to save them to your own db if you want to retrieve more.
