### ISSUE TITLE
Clan was cards api

### ISSUE THREAD

**Issue by rafarovina** [RoyaleAPI/cr-api#352]
Hi!

First of all, thank you for the awesome API =).

I'm here to suggest a new field for clan war endpoint.
I'd be really nice if I could see the cards the clan collected during collection day.
This would enable the clan so see how the collection is changing war to war.

`clanCards` would have the same structure as `cards` on the player endpoint.

## Request Details:
```
GET
https://api.royaleapi.com/clan/80LCC09P/war
```

## Response Details:
```
Code: 200
{
    "state": "collectionDay|warDay",
    "collectionEndTime": ...,
    "clan": {...},
    "participants": [...],
    "clanCards": [...],
}
```

**Comment by fourjr** [comment]
#333
