### ISSUE TITLE
Some members are missing in the war log

### ISSUE THREAD

**Issue by dagamargit** [RoyaleAPI/cr-api#353]
I have observed something strange related to war statistics. Some of the players of my clan are missing although they have participated in some wars. It seems to happen with new members.

I have observed in both, the web page (https://royaleapi.com/) and the API.

I can give you exact clan tag and missing member if needed (by private message).

Kind regards,
Daniel.

**Comment by fourjr** [comment]
Tag and missing member please, with in game screenshots. Send to the issue if possible, else `4JR#4895`

**Comment by dagamargit** [comment]
Hi,
I sent you a private message. Please, let me know if you have read it. I forgot to mention that the missing player appears in the webpage as current member but he doesn't appear in the war log analytics.

**Comment by dagamargit** [comment]
It was my fault!
The player never has participated in any war in my clan.

Sorry for the inconveniences.
