### ISSUE TITLE
Field filter uneffective on /player/:tag/battles endpoint

### ISSUE THREAD

**Issue by Tithanium** [RoyaleAPI/cr-api#354]
**Edit by fourjr**
GET https://api.royaleapi.com/clan/8PGGUR88/battles?keys=type returns expected results

GET https://api.royaleapi.com/player/2P0LYQ/battles?keys=type returns a blank dictionary 

**Original Issue**

As required by Selfish, I post the issue here.

It seams impossible to filter the data required to the API  /battles endpoints. 
For exemple, the request :

tag_radom1 = '2PRJ9CG9'
url = 'https://api.royaleapi.com/player/' + tag_radom1 +'/battles'
**provides an ok result such as expected.** The result contains 25 battles. Each battles have keys such as 
'type', 'mode, 'opponent', etc.

For example, I would like to filter the answer so that it returns only the 'type' from the battles. I would expect the endpoint to be 
url = 'https://api.royaleapi.com/player/' + tag_radom1 +'/battles?keys=type'
**Yet the answer is empty** : everything has been filtered out, and I expect this is due to the fact that the returned value should contain 25 battles, and in a second layer in the battles are the keys... thus the filtering remove all the battles since the keys are one layer deeper.

Similarily and for the same reason, excluding **does not work** on this endpoints 
url = 'https://api.royaleapi.com/player/' + tag_radom1 +'/battles?exclude=type'
**provides exaclty the same answer as the first endpoint**
url = 'https://api.royaleapi.com/player/' + tag_radom1 +'/battles'

Thanks for reading this Issue !

**Comment by Abhijeet589** [comment]
#339

**Comment by fourjr** [comment]
Issue 339 is not related to field filter. This is a different bug.

**Comment by selfish** [comment]
Great catch. resolved

**Comment by Tithanium** [comment]
Sorry to bother you again, but it seems there is still an issue...
For example, the following endpoint provides a lot of data for each player :
tag_radom1 = '2PRJ9CG9'
tag_radom2 = '2PRPRLLC'
url = 'https://api.royaleapi.com/player/' + tag_radom1 +',' + tag_radom2 + '/battles'
response = requests.request("GET", url, headers=headers)
testok1=response.json()
#
And the following enpoint provides exactly the same answer, even though it should only provide the battles type...
url = 'https://api.royaleapi.com/player/' + tag_radom1 +',' + tag_radom2 + '/battles?key=type'
response = requests.request("GET", url, headers=headers)
testok2=response.json()

Best,
Tithan

**Comment by fourjr** [comment]
keys not key

**Comment by fourjr** [comment]
and you should use the [clashroyale](https://github.com/cgrok/clashroyale) wrapper :eyes:

**Comment by Tithanium** [comment]
oh, ok !! Thanks. But, even though I didn't look into the clashroyal wrapper, why should I ? Is this better ?

**Comment by fourjr** [comment]
a wrapper will typically handle ratelimits, error handling and web requests so you don't have to deal with those
