### ISSUE TITLE
Pagination always returns the same page on player battles endpoint

### ISSUE THREAD

**Issue by rafadc** [RoyaleAPI/cr-api#356]
I do these two requests:

```
curl --header "auth: <my token>" "https://api.royaleapi.com/player/P2R2JL0JR/battles?page=1"
```

```
curl --header "auth: <my token>" "https://api.royaleapi.com/player/P2R2JL0JR/battles?page=2"
```

And they both return the first 25 battles of my user.

It is my first time using the API so I don't know if this was working before or not.

**Comment by fourjr** [comment]
The `max` url param also does nothing

**Comment by selfish** [comment]
Did some foolproofing to make sure there's no issue there, but keep in mind that `page` query param is meaningless without specifying `max` as well, which will decide how many results to return per page.
```sh
curl --header "auth: <my token>" "https://api.royaleapi.com/player/P2R2JL0JR/battles?max=3&page=1"
```
Will return different data from:
```sh
curl --header "auth: <my token>" "https://api.royaleapi.com/player/P2R2JL0JR/battles?max=3&page=2"
```
