### ISSUE TITLE
Popular decks

### ISSUE THREAD

**Issue by IlkkaPaananen** [RoyaleAPI/cr-api#360]
Hello, seekers! Could you in your api do a normal popular deck, like on your website, for example? That is, to integrate your site with the api and output detailed information about the decks in the endpoint of popular decks?

I also do a website on statistics, could you add tops to the clan trophies?

**Comment by fourjr** [comment]
Currently, there is a /popular/deck endpoint.

The website grabs data from player battles to determine the popular decks.
