### ISSUE TITLE
Clan war battles endpoint returning battles in random order

### ISSUE THREAD

**Issue by Abhijeet589** [RoyaleAPI/cr-api#367]
## Request Details:

```
GET
https://api.royaleapi.com/clan/LJ20/battles?type=war&max=50
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there?: Been there ever since I am trying
 2. Expected behavior: Return the latest war battles

I tried to get the latest war battles but instead, I am getting random battles, some as old as over 25 days and some just 1 day.
There's 3-4 collection day battles and in-between comes 1 war day attack.
It should return the latest war battles from the last/current war from all the members

**Comment by selfish** [comment]
Good catch. Corrected.
