### ISSUE TITLE
Endpoint tournament new filter  tournaments/notfull

### ISSUE THREAD

**Issue by Tithanium** [RoyaleAPI/cr-api#369]
Usually, the query with enpoints 
https://api.royaleapi.com/tournaments/open?prep=1
returns 100 open tournements... 

but it would be great to have an enpoint such as :
https://api.royaleapi.com/tournaments/open?notfull=1
to get tournaments tag that are not full from the API data. 
or 
https://api.royaleapi.com/tournaments/open?emptyslots=10
to get tournaments tag that have at least 10 empty slots ?

Would it be possible ?
Thanks again for all this work.

**Comment by fourjr** [comment]
Related to #284

**Comment by selfish** [comment]
Thanks for the idea. Might make this fancier in the future, for now:
Added `/joinable` endpoint, and `?joinable=1` param.
(As well as `/full` and `?full=q`)

[ @fourjr #docs ]

**Comment by fourjr** [comment]
This issue was moved to RoyaleAPI/cr-api-docs#37

**Comment by Tithanium** [comment]
I did try the endpoints 
https://api.royaleapi.com/tournaments/open?full=1
and 
https://api.royaleapi.com/tournaments/open?full=0

but didn't get different kind of results. What is this supposed to filter ?
Thanks in advance.

**Comment by fourjr** [comment]
full=0 and full=1 is the same thing.. use `joinable` to filter out not full tournaments

**Comment by Tithanium** [comment]
ok. I tried, but it find tournaments with supposedly max-1 personnes, and eventually, the next verification request find out it is already full...
