### ISSUE TITLE
?keys=

### ISSUE THREAD

**Issue by aclement1** [RoyaleAPI/cr-api#371]
### Idea/request:?keys=
![image](https://user-images.githubusercontent.com/39794652/41587886-8e0f2778-73b0-11e8-9d00-30bed8594317.png)
I would like to display just this information.

GET
https://api.royaleapi.com/players/LL22VG82?keys=arena
```

### Response Details:
<!-- Paste the exact response received from the server below: -->

```
Code: 200
![image](https://user-images.githubusercontent.com/39794652/41587978-cc7fc4b8-73b0-11e8-8838-94089c6f85ac.png)

Sorry for syntax i'm french and i have many difficult in english.

**Comment by fourjr** [comment]
not possible right now as you can only filter top level keys

**Comment by fourjr** [comment]
not possible.

**Comment by aclement1** [comment]
It's a shame, thank you
