### ISSUE TITLE
maintainance break error handling should be improved 

### ISSUE THREAD

**Issue by fourjr** [RoyaleAPI/cr-api#374]
### Request Details:

```
GET
https://api.royaleapi.com/player/2P0LYQ 
```

### Response Details:

```
Code: 503
{"Service Unavailable | Additional information and support: http://discord.me/royaleapi | Mention error ID undefined"}
```

might be related to https://github.com/RoyaleAPI/cr-api-ux/issues/155

note: maintenance break is currently ongoing

**Comment by selfish** [comment]
Error message updated to reflect that in upcoming rewrite. :)
