### ISSUE TITLE
royal hogs and giant snowball have no `id ` in /player/:tag["cards"] 

### ISSUE THREAD

**Issue by fourjr** [RoyaleAPI/cr-api#375]
GET https://api.royaleapi.com/player/2P0LYQ

Full response: https://hastebin.com/uqefubequt

**Comment by fourjr** [comment]
```json
{'name': 'Royal Hogs', 'level': 1, 'maxLevel': 11, 'count': 1, 'rarity': 'rare', 'requiredForUpgrade': 2, 'leftToUpgrade': 1, 'icon': 'https://api-assets.clashroyale.com/cards/300/ASSQJG_MoVq9e81HZzo4bynMnyLNpNJMfSLb3hqydOw.png'}
{'name': 'Giant Snowball', 'level': 1, 'maxLevel': 13, 'count': 16, 'rarity': 'common', 'requiredForUpgrade': 2, 'leftToUpgrade': -14, 'icon': 'https://api-assets.clashroyale.com/cards/300/7MaJLa6hK9WN2_VIshuh5DIDfGwm0wEv98gXtAxLDPs.png'}
```

normally the rarity would be `Common` or `Rare`, minor inconsistency which could break applications.

**Comment by fourjr** [comment]
This has been resolved (data is in /constants already) but leaving it open as you might want to improve no-constants behaviour

**Comment by selfish** [comment]
Actually, even though it's closed now, @fourjr - how would you suggest improving it?
