### ISSUE TITLE
Snowball and Royale Hog Card Link Invalid

### ISSUE THREAD

**Issue by Sid-Heart** [RoyaleAPI/cr-api#381]
https://api.royaleapi.com/player/82092289
Check his current deck, "snowball" and "royale hog" card's image link is not valid

**Comment by fourjr** [comment]
Please follow the issue template... and this is a game issue.

**Comment by Sid-Heart** [comment]
The image link is sent in api for each card.. the link sent for snowball and royale hog doesn't exist
