### ISSUE TITLE
Implement "since"-query parameter

### ISSUE THREAD

**Issue by olemartin** [RoyaleAPI/cr-api#385]
### Idea/request:
  1. It would be great to be able to send a "since" query-parameter to the battles endpoint. 
  1. I have a job that regulary check for new clan battles. Now I have to fetch all battles and filter out those I have already fetched. Would be great to do this filtering on your end. Would greatly reduce responsetime and network traffic
  1. Should apply to clan/battles and maybe player/battles
  1. Example: clan/battles?type=war&since=1529916954

**Comment by olemartin** [comment]
Any progress on this?

**Comment by selfish** [comment]
Nope.
Still in my to do. Have been extra busy with performance improvements lately.

**Comment by selfish** [comment]
Considering for V3
