### ISSUE TITLE
The clan.badgeName field in the tournament participants

### ISSUE THREAD

**Issue by IlkkaPaananen** [RoyaleAPI/cr-api#387]
Good afternoon. Previously there was a field clan.badgeName in the tournament participants, but for some reason it disappeared. 

Request: https://api.royaleapi.com/tournament/29C0908G

Returns now:
`{
	"tag": "29C0908G",
	"name": "Asciendeme Ulises :v",
	"open": true,
	"maxPlayers": 100,
	"currentPlayers": 100,
	"status": "inProgress",
	"createTime": 1530055637,
	"prepTime": 7200,
	"startTime": 1530062426,
	"endTime": null,
	"duration": 3600,
	"description": "El que gane que ulises lo ascienda jajajajajaja menos a fuentes jaja ntc es broma carnalito рџ‚вњЊрџЏ»",
	"updatedAt": 1530065562,
	"maxCapacity": 100,
	"playerCount": 100,
	"preparationDuration": 7200,
	"type": "open",
	"creator": {
		"tag": "2VJJ908JJ",
		"clan": {
			"tag": "2992QYPV",
			"name": "Polybius",
			"badgeId": 16000153
		},
		"name": "VictorEstal",
		"rank": 18,
		"score": 86,
		"creator": true
	},
	"members": [{
		"tag": "2PRUL9GVG",
		"clan": {
			"tag": "2LYJLQJ",
			"name": "Ш§ШіЩ€ШЇ Ш§Щ„Ш±Ш§ЩЃШЇЩЉЩ†",
			"badgeId": 16000041
		},
		"name": "Ш¶Ш§ШєШ·Щ‡Щ… ШЁШґШ®ШµШЄЩЉ",
		"rank": 1,
		"score": 242
	}
...`

It is necessary to return (as it was before, and why this field was removed):

`{
	"tag": "29C0908G",
	"name": "Asciendeme Ulises :v",
	"open": true,
	"maxPlayers": 100,
	"currentPlayers": 100,
	"status": "inProgress",
	"createTime": 1530055637,
	"prepTime": 7200,
	"startTime": 1530062426,
	"endTime": null,
	"duration": 3600,
	"description": "El que gane que ulises lo ascienda jajajajajaja menos a fuentes jaja ntc es broma carnalito рџ‚вњЊрџЏ»",
	"updatedAt": 1530065562,
	"maxCapacity": 100,
	"playerCount": 100,
	"preparationDuration": 7200,
	"type": "open",
	"creator": {
		"tag": "2VJJ908JJ",
		"clan": {
			"tag": "2992QYPV",
			"name": "Polybius",
			"badgeId": 16000153,
                        "badgeName": "A_Char_Rocket_02" (for example) @@@@@@@@@@@@@
		},
		"name": "VictorEstal",
		"rank": 18,
		"score": 86,
		"creator": true
	},
	"members": [{
		"tag": "2PRUL9GVG",
		"clan": {
			"tag": "2LYJLQJ",
			"name": "Ш§ШіЩ€ШЇ Ш§Щ„Ш±Ш§ЩЃШЇЩЉЩ†",
			"badgeId": 16000041,
                        "badgeName": "A_Char_Rocket_02" (for example) @@@@@@@@@@@@@
		},
		"name": "Ш¶Ш§ШєШ·Щ‡Щ… ШЁШґШ®ШµШЄЩЉ",
		"rank": 1,
		"score": 242
	},`

**Comment by fourjr** [comment]
Might be related to #380

**Comment by selfish** [comment]
Is this happening in dev server?

**Comment by fourjr** [comment]
Yes ![image](https://user-images.githubusercontent.com/28086837/42149589-6de85b00-7e09-11e8-9dd9-6be675fc34a3.png)

**Comment by selfish** [comment]
Is this still relevant in main API?
Feel free to reopen if it is.
