### ISSUE TITLE
All API requests result in an HTTP Error 429 with an expiration date one minute in the past.

### ISSUE THREAD

**Issue by janole** [RoyaleAPI/cr-api#390]
### Issue Report:

All of my API requests result in an HTTP Error 429, even when I am stopping using the API and trying again after half an hour.

  1. Did you encounter this recently, or has this bug always been there?

Yes, this seems to have started yesterday.

  2. Expected behaviour: 

Regular API responses without an 429 Limit Reached.

  3. Further details about the key used:

I've already reset the key once but to no avail.

"md": {
    "username": "janole",
    "keyVersion": 3,
    "discriminator": "2295"
  },

**Comment by selfish** [comment]
Resolved temporarily manually, and upcoming rewrite of the API will resolve permanently.
