### ISSUE TITLE
Improve error handling in batch requests

### ISSUE THREAD

**Issue by Anton3** [RoyaleAPI/cr-api#391]
### Idea
Add "exists" field for `/player` and `/clan` endpoints. For batch requests, if some players or clans don't exist, the response should still include other players.

### Rationale
Currently, in a request for multiple players or clans, if any of them does not exist, the API returns error for the whole request. I try to use batch requests with many tags whenever possible, but if the API returns error, I have to send individual requests instead, trying to find out, which account was banned, or which clan no longer exists. This leads to longer delays.

### Affected endpoints
- `/player/:tag`
- `/player/:tag/battles`
- `/player/:tag/chests`
- `/clan/:tag`
- `/tournament/:tag`

### Request Details:

```
https://api.royaleapi.com/player/0V0Q00VV
```

### Response Details:

```
Code: 200
{
  "exists": false,
}
```

### Request Details:

```
https://api.royaleapi.com/player/9VQUCULU,0V0Q00VV
```

### Response Details:

```
Code: 200
[
  {
    "exists": true,
    <the rest of info goes here>
  },
  {
    "exists": false
  }
]
```

**Comment by fourjr** [comment]
I feel that 404 should still be returned in both cases
