### ISSUE TITLE
devapi and api return lists for single tag requests sometimes

### ISSUE THREAD

**Issue by fourjr** [RoyaleAPI/cr-api#392]
### Issue Report:
  1. Did you encounter this recently, or has this bug always been there? Very recently
  1. Expected behaviour: A list should not appear if only one tag is given

I managed to reproduce this on my browser with `devapi`. 
![image](https://user-images.githubusercontent.com/28086837/42144186-679792ba-7dec-11e8-9866-1239ff96c372.png)

My application, that uses `api` kept reporting that the data returned was an array instead of an object.

This does not happen 100% of the time. 

### Request Details:

```
GET
https://api.royaleapi.com/player/2P0LYQ/chests
https://devapi.royaleapi.com/player/2P0LYQ/chests
```

### Response Details:

```json
[
  {
    "upcoming": [
      "silver",
      "silver",
      "silver",
      "silver",
      "gold",
      "silver",
      "silver",
      "silver",
      "silver"
    ],
    "superMagical": 129,
    "magical": 17,
    "legendary": 52,
    "epic": 53,
    "giant": 92
  }
]
```

**Comment by selfish** [comment]
I'm completely unable to reproduce this =\
Is it still happening?

**Comment by Gr8z** [comment]
cannot reproduce on devapi nor api

**Comment by selfish** [comment]
@fourjr - please close if irrelevant

**Comment by fourjr** [comment]
i just got it again 🤔

**Comment by selfish** [comment]
*sigh*

**Comment by fourjr** [comment]
The first time i requested, it was an object, second time onwards, became an array.. happened for 3 other tags

**Comment by selfish** [comment]
This was a cache issue.
Surely, it must be resolved now.
Please reopen if still occurring (I was able to find steps to reproduce, and eliminated the issue)
