### ISSUE TITLE
undefined unauthorised error

### ISSUE THREAD

**Issue by fourjr** [RoyaleAPI/cr-api#393]
### Issue Report:
  1. Did you encounter this recently, or has this bug always been there? Not sure, never tested this
  1. Expected behaviour: `"message": "Forbidden, no authorization provided | Additional information and support: http://discord.me/royaleapi"`
  1. Console logs (if applicable): 
  1. Screenshots (if applicable):

### Request Details:

```
GET
https://devapi.royaleapi.com/player/PQQ0Q8CG/chests
```

### Response Details:

```json
{
    "error": true,
    "status": 403,
    "message": "undefined | Additional information and support: http://discord.me/royaleapi"
}
[HTTP 403]
```

Invalid tokens work fine, undefined occurs when no token is provided
```json
{
    "error": true,
    "status": 401,
    "message": "Unauthorized; unknown token | Additional information and support: http://discord.me/royaleapi"
}
[HTTP 401]
```

**Comment by selfish** [comment]
Fixed on dev server (live)
