### ISSUE TITLE
cache issues in dev server

### ISSUE THREAD

**Issue by fourjr** [RoyaleAPI/cr-api#394]
### Issue Report:
  1. Did you encounter this recently, or has this bug always been there? Recently
  1. Expected behaviour: Maintaince break error

### Request Details:

```
GET
https://devapi.royaleapi.com/player/2P0LYQ/chests
```

### Response Details:

```
Code: 200
{
  "error": true,
  "status": 500,
  "message": "[{\"upcoming\":[\"silver\",\"silver\",\"silver\",\"silver\",\"gold\",\"silver\",\"silver\",\"silver\",\"silver\"],\"superMagical\":129,\"magical\":17,\"legendary\":52,\"epic\":53,\"giant\":92}] | Additional information and support: http://discord.me/royaleapi | Mention error ID 4c18a454b0594100bb91019fd2ce0830"
}
```

This is definitely cached data from a while ago, I did not request in the past half an hour.
Headers returned (except the 3 ratelimit headers)
![image](https://user-images.githubusercontent.com/28086837/42153542-f8d46842-7e15-11e8-8192-0e7e28ff6201.png)

Other endpoints like /top/players that I have not requested in a while works

**Comment by selfish** [comment]
Fixed.
