### ISSUE TITLE
"Keys" and "exclude" filters not working (field filter)

### ISSUE THREAD

**Issue by fourjr** [RoyaleAPI/cr-api#395]
### Request Details:

```
GET
https://devapi.royaleapi.com/player/2P0LYQ?keys=name
https://devapi.royaleapi.com/player/2P0LYQ?exclude=name
```

### Response Details:

We get the full json response instead of a filtered one

**Comment by Tithanium** [comment]
+1 for url like 
'http://api.royaleapi.com/player/2RL0QJUL9?keys=name,cards'

**Comment by antonioreyna** [comment]
i have this same issue

**Comment by Gr8z** [comment]
Confirmed issue

**Comment by selfish** [comment]
Might be considered for V3
