### ISSUE TITLE
error 500 when I slightly modify my api key

### ISSUE THREAD

**Issue by fourjr** [RoyaleAPI/cr-api#396]
### Request Details:

```
GET
https://devapi.royaleapi.com/player/2P0LYQ/chests 
```

### Response Details:

```json
{
  "error": true,
  "status": 500,
  "message": "Internal Server Error | Additional information and support: http:\/\/discord.me\/royaleapi | Mention error ID 571591c31678468f9e5fe491fa78b525"
}

[HTTP 500] 
```

Request with one random character added to the front of your developer key.

The endpoint works normally on my correct developer key.

Expected result: an unauthorised error with invalid authentication, http 401 or 403 and not 500

**Comment by selfish** [comment]
Changed to 401
