### ISSUE TITLE
days parameter in history endpoint not working

### ISSUE THREAD

**Issue by Sagi44** [RoyaleAPI/cr-api#397]
I suspect that the history endpoint is not respecting the "days" parameter as described in :

https://docs.royaleapi.com/#/endpoints/clan_history

### Request Details:
GET
https://api.royaleapi.com/Clan/PPYJ0V/history?10
Should return last 10 ClanHistoryRecords.
Instead Returns ALL ClanHistoryRecords ever since tracking enabled..

**Comment by Gr8z** [comment]
I think you misunderstood the parameter. 
The "?days" query string can be specified to limit the number of days of data to return. That does not mean doing `?days=2` will return 2 results. One day can have multiple results as your clan is tracked every 4 hours.

**Comment by Sagi44** [comment]
Thanks.

**Comment by Gr8z** [comment]
No, you should not. API can do offline or game can have maintenance which can lead you your clan not being tracked at the scheduled time. Making it possible not to have 6 records of history per day. You should not rely on counting but should check the timestamp in your application.
