### ISSUE TITLE
War Analytics List IMCOMPLETE

### ISSUE THREAD

**Issue by Alpha185** [RoyaleAPI/cr-api#402]
### Show every clan member in the war list, even who never participated:
  Who never participated in a clan war is not showing up at the list, I propose that if a player is part of the clan and doesn't participate at a war then you mark a dash "-" at the space provided for the medal icon.
This way I know who's being inactive 
If the player was not at the clan then you leave it blank

https://royaleapi.com/clan/UR9290J/war/analytics

**Comment by Gr8z** [comment]
Please specify, Is this for the API for the website?

**Comment by Alpha185** [comment]
at the WAR ANALYTICS list I cant see the players that never participated in
a clan war

https://royaleapi.com/clan/UR9290J/war/analytics

so if a player is at the clan and doesnt participate you could put a dash
"-" at  the space reserved for the medal picture

Please put ALL the clan members at the list, it will help me to see wich
players arent playing

sorry, I dont know what API stands for

Cordialmente,

Mauro Gyotoku
+55 11 98546-1000

2018-07-05 10:28 GMT-03:00 GR8 <notifications@github.com>:

**Comment by Alpha185** [comment]
![image](https://user-images.githubusercontent.com/40841806/42344416-ac9366c2-8072-11e8-9706-7887955c11a8.png)

something like this

**Comment by Alpha185** [comment]
![image](https://user-images.githubusercontent.com/40841806/42344595-345458dc-8073-11e8-93b0-217a50b41c77.png)

**Comment by Alpha185** [comment]
with a dash I'll know that the player was actually at the clan and did not participate
if it's blank it's because he was not at the clan
I don't know anything about a programming but I guess I'm not requesting much since I can do this with Excell
Anyways, I love this website, it saves me a lot of time, cheers!

**Comment by fourjr** [comment]
This issue was moved to RoyaleAPI/cr-api-docs#41
