### ISSUE TITLE
[Request] Change percent calculations

### ISSUE THREAD

**Issue by crapirobili** [RoyaleAPI/cr-api#406]
### Idea/request:
  1. Briefly explain the idea or request.
  - Change the wins-, losses- and drawpercentage calculations to only use wins and losses and ignore draws and total. For instance: winsPercent = wins / (wins + losses).

  1. Briefly explain the rationale behind the request, or provide a use case.
  - The current calculations use the draw values that are derived and very much non reliable as they are mixed up with all kinds of values (like 2vs2 data). For any player not just playing 1vs1, the percentage values will be off in a non-obvious way as the naming is confusing. 

It's questionable if draws should be exposed at all especially under that name), considering that they're not really draws, but at least calculations shouldn't be made on top of them.

  1. In which request/endpoint does this apply?
  - player

  1. Use the boxes at the bottom of this template to demonstrate a request and expected response.
  - N/A

**Comment by Gr8z** [comment]
We give you the data returned from the application. However, you can easily do these simple calculations on your own application.

**Comment by selfish** [comment]
While everything you wrote makes general sense, I believe people's stats rely on all of this. Can't really make changes at this stage.
