### ISSUE TITLE
Setting Max and Page number for battles not working (Pagination)

### ISSUE THREAD

**Issue by rprescottjr** [RoyaleAPI/cr-api#407]
### Issue Report:
  1. Did you encounter this recently, or has this bug always been there? I just encountered this recently, although I have not tried to use this functionality before.
  1. Expected behaviour: When setting a max value, a maximum of that many results is included in the resultset. When setting a page value, paging properly happens.

### Request Details:
```
GET
https://api.royaleapi.com/clan/22082YC0/battle?type=war&max=2&page=1
https://api.royaleapi.com/clan/22082YC0/battle?type=war&max=2&page=0
```

### Response Details:
```
Code: 200
Due to the length of the response, a screenshot is included below with just the first couple results...
```
![image](https://user-images.githubusercontent.com/37492010/42412747-3dd9b87a-81e0-11e8-9ca3-625eec6c2669.png)

**Comment by Gr8z** [comment]
`exclude` and `keys` params are not working either.
