### ISSUE TITLE
1 member history

### ISSUE THREAD

**Issue by PeterZhisov** [RoyaleAPI/cr-api#408]
### Idea/request:
  1. Briefly explain the idea or request.
  1. Briefly explain the rationale behind the request, or provide a use case.
  1. In which request/endpoint does this apply?
  1. Use the boxes at the bottom of this template to demonstrate a request and expected response.

### Issue Report:
  1. Did you encounter this recently, or has this bug always been there?
  1. Expected behaviour: 
  1. Console logs (if applicable): 
  1. Screenshots (if applicable):

### Request Details:

```
GET
https://api.royaleapi.com/top/clans
```

### Response Details:

```
Code: 200
[...]
```

**Comment by Gr8z** [comment]
Issue template not properly filled, the given URL is working fine.
