### ISSUE TITLE
[REQUEST] Add seasonNumber to current clan war data

### ISSUE THREAD

**Issue by ahdavis** [RoyaleAPI/cr-api#409]
1. Request to please add `seasonNumber` to all war data so that when pulling individual clan war data, we know which season it is.
 2. When charting current clan war data with past clan war data, it would be very useful to know what season the current war data is for.
 3. In which request/endpoint does this apply? `https://api.royaleapi.com/clan/<TAG>/war`

**Comment by fourjr** [comment]
Please comment on #333
