### ISSUE TITLE
[REQUEST] Pull clan war data for multiple clans

### ISSUE THREAD

**Issue by ahdavis** [RoyaleAPI/cr-api#410]
1. Request to have a clan war endpoint for multiple clans similarly to pulling clan data for multiple clans (`https://api.royaleapi.com/clan/<TAG1>,<TAG2>`).
  2. Would be very convenient and less network bandwidth to pull clan war data for multiple clans with one query.
  3. In which request/endpoint does this apply? `https://api.royaleapi.com/clan/<TAG>/war`, possibly allow it to support this: `https://api.royaleapi.com/clan/<TAG1>,<TAG2>,.../war` or `https://api.royaleapi.com/clan/war/<TAG1>,<TAG2>,...`

**Comment by fourjr** [comment]
This is probably due to an internal limitation.. also, please comment on #333
