### ISSUE TITLE
Tournaments endpoint not returning type

### ISSUE THREAD

**Issue by ZeNeLLiE** [RoyaleAPI/cr-api#413]
https://api.royaleapi.com/tournaments/search?name=b

type is not returned. ("open", "passwordProtected")

Expected:

> [
>     {
>         "tag": "20CVYRV8",
>         "type": "open",
>         "status": "inPreparation",
>         "creatorTag": "#99Y90URP8",
>         "name": "Andrei Geanta",
>         "maxCapacity": 50,
>         "preparationDuration": 7200,
>         "duration": 3600,
>         "createTime": 1520249970,
>         "startTime": null,
>         "endTime": null,
>         "playerCount": 50,
>         "members": []
>     },
>     {
>         "tag": "C9LRLP0",
>         "type": "passwordProtected",
>         "status": "inProgress",
>         "creatorTag": "#989G8QLCG",
>         "name": "ali",
>         "description": "vous pouvez pas rejoindre",
>         "maxCapacity": 100,
>         "preparationDuration": 7200,
>         "duration": 3600,
>         "createTime": 1520251673,
>         "startTime": null,
>         "endTime": null,
>         "playerCount": 29,
>         "members": []
>     },
> ]

Actual:

>  {
>         "tag": "29CV0PQG",
>         "name": "bora jogar",
>         "open": true,
>         "maxPlayers": 50,
>         "currentPlayers": 50,
>         "status": "inProgress",
>         "createTime": 1532564781,
>         "prepTime": 7200,
>         "startTime": null,
>         "endTime": null,
>         "duration": 3600,
>         "description": "entra quem quiser",
>         "updatedAt": 1532571124,
>         "members": []
>     },

**Comment by Altarrel** [comment]
This is expected behaviour
![image](https://user-images.githubusercontent.com/31830955/43237683-e7258248-9058-11e8-9575-7c3feb17a455.png)

**Comment by fourjr** [comment]
This issue was moved to RoyaleAPI/cr-api-docs#47
