### ISSUE TITLE
War Analytics missing "missed battle" with a "win"

### ISSUE THREAD

**Issue by Magik11** [RoyaleAPI/cr-api#417]
### Issue Report:
  1. Did you encounter this recently, or has this bug always been there?
Recently; today.
  2. Expected behaviour: 
For https://royaleapi.com/clan/RP2P8V/war/analytics, player doa1, his last war battle included 2 battles; one was a win the other he missed. Only the win is displayed on the web page. I expect it to show both the win medal and the empty medal. Only the win medal is shown.
  3. Console logs (if applicable): 
n/a
  4. Screenshots (if applicable):

### Request Details:

Use a browser and visit https://royaleapi.com/clan/RP2P8V/war/analytics.

**Comment by fourjr** [comment]
This issue was moved to RoyaleAPI/cr-api-ux#244
