### ISSUE TITLE
Wrong sample response for endpoints clan_war under state matchmaking in docs

### ISSUE THREAD

**Issue by henrywkk** [RoyaleAPI/cr-api#418]
### Issue Report:
Under the doc for clan war (https://docs.royaleapi.com/#/endpoints/clan_war), the **state** in Matchmaking sample should be "matchmaking" instead of "collectionDay" (https://docs.royaleapi.com/json/clan_war_80LCC09P.json)

**Comment by fourjr** [comment]
This issue was moved to RoyaleAPI/cr-api-docs#52
