### ISSUE TITLE
[Request] Matchup endpoint for popular decks

### ISSUE THREAD

**Issue by Anton3** [RoyaleAPI/cr-api#421]
### Idea
For some decks ("popular" decks), provide a list of popular matchups with their results (# of wins, # of draws, # of losses).

### Rationale
The data is already collected for [RoyaleAPI](royaleapi.com). It can be used for creating nice diagrams of current meta and for recommending decks to use in specific conditions.

### Request Details:
```
GET
https://api.royaleapi.com/deck/cannon-cart,furnace,graveyard,ice-golem,inferno-dragon,poison,rascals,the-log?battle_type=All
```

`battle_type` should be one of: `All`, `LadderTop200`, `Ladder4K`, `GC`.

### Response Details:

```
Code: 200
{
  "cards": [
    {
      "key": "cannon-cart",
      // ... other fields describing the card
    },
    // ... other cards
  ],
  "decklink": // ...
  "popularity": // ...
  "matchups": [
    {
      "cards": [
        // ...
      ],
      "win": // ...
      "draw": // ...
      "loss": // ...
    },
    // other matchups
  ] 
}
```

**Comment by selfish** [comment]
That you should do on your on big-data cluster. :X
Would love to, but I don't have the funds to start offering big data analysis to the public.
https://royaleapi.com/donate
