### ISSUE TITLE
Getting 404 error when using clan search endpoint

### ISSUE THREAD

**Issue by YourMomCR** [RoyaleAPI/cr-api#423]
### Issue Report:
  1. Was working yesterday, but has not worked for me today
  1. Expected response back from api call - getting 404 error instead.

### Request Details:
Get("http://api.royaleapi.com/clan/search?&score=44400&locationId=_NA&max=500&keys=tag,name,type,score")

### Response Details:
System.Net.WebException occurred
  HResult=0x80131509
  Message=The remote server returned an error: (404) Not Found.
  Source=System

**Comment by YourMomCR** [comment]
Seems to be the locationId that is causing the issue.  Removing it does allow the call to work, but I am wanting to retrieve using the locationId.

**Comment by ijm8710** [comment]
No rush at all! Thanks

Question for you or sml.

On github I generally use githawk. I’ve been getting oath 3rd party restriction squawks constantly in this repo. Codehub works fine and of course if I have to, I can use GitHub website. Do you guys have the repo set up perhaps leading to these restrictions, or is it an issue with githawk solely. I help beta test for githawk and they haven’t diagnosed, hence why I’m curious.

**Comment by selfish** [comment]
Not at all. I'd contact the app's support.

One more request, please separate questions to different issues in the future.

**Comment by selfish** [comment]
Can't reproduce rn.
I believe ou were getting 404 because no clans matched the parameters.
