### ISSUE TITLE
Clan history snapshots not generated

### ISSUE THREAD

**Issue by gabor-rajczi** [RoyaleAPI/cr-api#428]
Yesterday I enabled the clan history.

If I send this request:
https://api.royaleapi.com/clan/8UP9PC9L/tracking
I get the response:
{"tag":"8UP9PC9L","active":true,"available":true,"snapshotCount":2}

It looks good.
But I get this result always.
Just 2 snapshot is available.
No additional snapshot is generated.

Today I send this request:
https://api.royaleapi.com/clan/8UP9PC9L/history
And get this response:
{"error":true,"status":417,"message":"Clan not tracked | Additional information and support: http://discord.me/royaleapi"}

But in the first response, I see, the tracking is active, and available.

If I lookup for this URI:
https://royaleapi.com/clan/8UP9PC9L/history?field=donations&time=7d

I see, there is snapshots.

I resend this request:
https://api.royaleapi.com/clan/8UP9PC9L/history

And get the response as excepted. There is 2 snapshots.
One is from 2018-09-04-16-00, and the other is from 2018-09-04-20-00.

How can it be?
What make I wrong?

**Comment by fourjr** [comment]
This was due to API being down. History is back up.
