### ISSUE TITLE
Error 503 Endpoint Players

### ISSUE THREAD

**Issue by SOSkr** [RoyaleAPI/cr-api#429]
### Issue Report:
When I consult the Player EndPoint with more than 1 player, I get an error

### Request Details:
https://api.royaleapi.com/player/G2RVLUP,20CRRQ9CY,LCR800YU,QULU8P8,QL0VJVPP

### Response Details:
{
    "error": true,
    "status": 503,
    "message": "Game servers can't be reached. This may be due to maintenance break. | Additional information and support: http://discord.me/royaleapi | Mention error ID 41f7e3aa3a1a4984b5f1119c828d5ca2",
    "maintenanceBreak": true
}

**Comment by amirhossein99** [comment]
Yes me tooooooo

**Comment by briankates816** [comment]
same.  broken

**Comment by amirhossein99** [comment]
yes

**Comment by fourjr** [comment]
API status is back up. Please do not create issues for api being down, these are usually resolved within the discord server.
