### ISSUE TITLE
getiing 403 on requests

### ISSUE THREAD

**Issue by keshavbhatt** [RoyaleAPI/cr-api#432]
### Issue Report:
  1. Did you encounter this recently, or has this bug always been there?
Recently
  1. Expected behaviour: 
getting 403

make simple request using your api key using curl
 
### Request Details:
curl --header "auth: myAPIkey" https://api.royaleapi.com/player/8g2gy00r 

GET
https://api.royaleapi.com/top/clans
```

### Response Details:
{"error":true,"status":403,"message":"Response code 403 (Forbidden) | Additional information and support: http://discord.me/royaleapi"}

```
Code: 403
```

**Comment by gabebor** [comment]
same issue for me too

**Comment by fourjr** [comment]
This issue is being reported in the discord server. API down issues shouldn't be in github issues.
