### ISSUE TITLE
Discord user dirtmelon has a great app of royaleapi in beta. I requested for collections played data to be included in app like it is in site. He said that data is not public. Can you release that data please?

### ISSUE THREAD

**Issue by ijm8710** [RoyaleAPI/cr-api#437]

**Comment by selfish** [comment]
No idea what you're talking about.

**Comment by ijm8710** [comment]
Passionate user has introduced a sweet mobile app for royaleapi!

![GitHawk Upload by ijm8710](https://i.imgur.com/3Vl4gUK.jpg)

You guys track collection battles played:)
![GitHawk Upload by ijm8710](https://i.imgur.com/A2aT6oJ.jpg)

Their app does not, so I requested it
![GitHawk Upload by ijm8710](https://i.imgur.com/0iPltcR.jpg)

His response was that “Yes, the site can show the battles number of collection day, but the public api doesn't provide them when in war day or war histories”. Surprising, but was curious if there’s any way for that info to be included in the public api since you guys obviously have that data now in order to display it. Might be a @smlbiobot question. Also curious, you guys display it for war log, but not for active war on war day. Curious if that is displayable as well.

**Comment by ijm8710** [comment]
@smlbiobot do you have any idea if his app would use the public api or build views off royale api itself. There are a few things you guys do very well that he says he doesn’t have access to, but this sounds surprising because I feel anything you guys build off of, you make public anyway. 

There are a few examples, but the first I referenced is he said that “collections played” data which you recently git is not public. Is this correct?
