### ISSUE TITLE
401 error every time I try to list clan battles.

### ISSUE THREAD

**Issue by fjcsc** [RoyaleAPI/cr-api#438]
### Issue Report:
  1. Did you encounter this recently, or has this bug always been there?
  
   It is a new issue. I'm getting the 401 error every time I try to list my clan battles.

### Request Details:

```
curl -X GET \
   https://api.royaleapi.com/clan/CLAN_TAG/battles \
   -H 'Authorization: Bearer XXXXXXX \
   -H 'Cache-Control: no-cache'

```

### Response Details:
{"error": true, "status": 401, "message": "Response code 401 (Unauthorized) | Additional information and support: http://discord.me/royaleapi%22%7D

```
Code: 401

```
Also noticed that when I try to access battles using the player end point (https://api.royaleapi.com/player/<TAG>/battles), everything works normally. 

But if I try to list battles using multiple tags (https://api.royaleapi.com/player/<TAG>,<TAG>,<TAG>/battles) I get the same 401 error.

Can you give me some light on that @selfish ?
Thanks a lot!

**Comment by gabebor** [comment]
similar to me but i receive 401 from time to time on the war endpoint. after some minutes same loop is working again.

**Comment by fjcsc** [comment]
In fact I'm receiving intermittent 401 errors. Most of them are "solved" if I run the script again. The only endpoint that never responds (always receiving 401) is the ...clantag/battle. I do understand that this is a heavy query ... so maybe everybody may be locked out at the moment.

**Comment by selfish** [comment]
What's the response code?
