### ISSUE TITLE
RequiredForUpgrade has two data types

### ISSUE THREAD

**Issue by zKashu** [RoyaleAPI/cr-api#442]
### Issue Report:
  1. Did you encounter this recently, or has this bug always been there?
  Recently
  1. Expected behaviour: 
  Not sure on what I should put here
  1. Console logs (if applicable): 
  `com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "Maxed"`
  1. Screenshots (if applicable):

Use the player tag of a player who has at least one max level card.

The attribute `requiredForUpgrade` inside the card object of a "Max Level" card will say "Maxed" while the rest of the cards will have an integer amount.

The attribute cannot be both integer & string.
### Request Details:
```
GET
https://api.royaleapi.com/player/82RJJG902
```

### Response Details:

```
I only get a throwable, which says `"com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "Maxed""`
```

**Comment by selfish** [comment]
Read the docs. :)
This value is either a numeric amount, or a string "Maxed".
