### ISSUE TITLE
superMagical always 0

### ISSUE THREAD

**Issue by Zheng-Shuo** [RoyaleAPI/cr-api#443]
hi, when I request the "GET https://api.royaleapi.com/player/<TAG>/chests" api it response 
"{
    "upcoming": [
        "silver",
        "gold",
        "silver",
        "silver",
        "gold",
        "silver",
        "silver",
        "silver",
        "gold"
    ],
    "superMagical": 0,
    "magical": 33,
    "legendary": 53,
    "epic": 395,
    "giant": 20
}", my question is why is the "superMagical" is 0?

**Comment by selfish** [comment]
It was removed from the game last update I think, no?
If not, I think there's also something about reaching a certain level before you get super-magicals or smth.
