### ISSUE TITLE
Track Mega Lightning Chest

### ISSUE THREAD

**Issue by Darkoman25** [RoyaleAPI/cr-api#444]
### Idea/request:
  Please add the Mega Lightning Chest to the chest tracker on player pages.

**Comment by Darkoman25** [comment]
This has been resolved

**Comment by Zheng-Shuo** [comment]
Has this change been updated to "https://api.royaleapi.com/player/<TAG>/chests" API?
I can't get the Mega Lightning Chest through "https://api.royaleapi.com/player/<TAG>/chests" API.

**Comment by selfish** [comment]
Implemented.
