### ISSUE TITLE
Add "tournament type" in tournament request

### ISSUE THREAD

**Issue by Tithanium** [RoyaleAPI/cr-api#446]
Now that tournaments are of many type (triple elixir, normal, reference, etc), could we have the type of tournament in the output enpoint 
'https://api.royaleapi.com/tournaments/#tag" ,
or, even better, a filter that can request only one type of tournament output...
Thanks,
Tithan

**Comment by selfish** [comment]
Great idea!

**Comment by selfish** [comment]
Will be added in V3
