### ISSUE TITLE
Missing location code for Oceania clan locations

### ISSUE THREAD

**Issue by Tr-Jono** [RoyaleAPI/cr-api#447]
## Issue Report:
  1. I encountered this today, no idea if it was there before.
  2. Expected behaviour: `"code": "_AU"` is present in `clan["location"]`. ([Location code for Oceania](https://github.com/RoyaleAPI/cr-api-data/blob/master/json/regions.json#L28) is `_AU`)
  3. This only happens to Oceania clans retrieved from `/clan`, `/top/clans` and `/top/war`, not to clans in other regions such as Asia.

### Request Details:
```
GET
https://api.royaleapi.com/clan/89YVRV
https://api.royaleapi.com/top/clans
https://api.royaleapi.com/top/war
```

### Response Details:
`/clan/89YVRV` (some data is omitted):
```
Code: 200
{
  "tag": "89YVRV",
  "name": "DBZ Saiyans",
  "description": ...,
  "type": "open",
  "score": 51050,
  "warTrophies": 8971,
  "memberCount": 46,
  "requiredScore": 4900,
  "donations": 28006,
  "badge": {...},
  "location": {
    "name": "Oceania",
    "isCountry": false
  },
  "members": [...],
  "tracking": {...}
}
```

`/top/clans` and `/top/war` (similar response, some data is omitted):
```
Code: 200
[
  ...,
  {
    "tag": "89YVRV",
    "name": "DBZ Saiyans",
    "score": 8971,
    "memberCount": 46,
    "rank": ...,
    "previousRank": ...,
    "badge": {...},
    "location": {
      "name": "Oceania",
      "isCountry": false
    }
  },
  ...
]
```

**Comment by selfish** [comment]
It has no location code AFAIK, and doesn't exist in the official API.
Feel free to reopen with details if I'm incorrect.
