### ISSUE TITLE
Endpoint `/top/*/_AU` not functioning

### ISSUE THREAD

**Issue by Tr-Jono** [RoyaleAPI/cr-api#448]
## Issue Report:
  1. I encountered this today, no idea if it was there before.
  2. Expected behaviour: A list of Oceania clans should be returned in `/top/clans/_AU` and `/top/clans/_AU` instead of 400.
  3. #447 may be related.

### Request Details:
```
GET
https://api.royaleapi.com/top/clans/_AU
https://api.royaleapi.com/top/war/_AU
```

### Response Details:
The response is the same in both requests.
```
Code: 400
{
  "error": true,
  "status": 400,
  "message": "Invalid location (not found) | Additional information and support: http://discord.me/royaleapi"
}
```

**Comment by selfish** [comment]
AFAIK, this was removed from the official API, which we rely on for this endpoint.
If you have it there share the details and I'll correct it.
