### ISSUE TITLE
Intermittent 503 Service Unavailable for /clan/<tag>/battles and /clan/<tag>/warlog endpoints

### ISSUE THREAD

**Issue by mwolverine63** [RoyaleAPI/cr-api#449]
### Issue Report:
I have encountered this issue over the last few days. I haven't been pulling data more recently than a few days ago. Sometimes the request will succeed and sometimes it will fail, I have not observed a pattern with respect to clan tag.

### Request Details:

```
GET
https://api.royaleapi.com/clan/9JUPGCP2/battles
https://api.royaleapi.com/clan/8QQUCUQY/warlog
```
This is failing for more than just that clan, but that is an example of the request.

### Response Details:

```
Code: 503
Service Unavailable
```

**Comment by selfish** [comment]
Should be resolved by now.
Feel free to re-open if not.

**Comment by mwolverine63** [comment]
Noticed this issue again at ~11:50 PM UTC
