### ISSUE TITLE
Feature : Trade Tokens endpoint for each player

### ISSUE THREAD

**Issue by antares-farias** [RoyaleAPI/cr-api#450]
### Idea/request:
  1. Have an endpoint to trade tokens
  2. This will help to make trade more efective

### Request Details:

```
GET
https://api.royaleapi.com/players/<TAG>/tokens
```

### Response Details:

```
[
    {
        "type": "legendary",
        "amount": "2",
   }
...
]
```

**Comment by bobbelsche** [comment]
nice idea 👍

**Comment by bricecarbou** [comment]
It seems to me that token information is not accessible on the official CR api ?

**Comment by selfish** [comment]
No token info available to me.
