### ISSUE TITLE
Getting player info doesn't list the maxed cards

### ISSUE THREAD

**Issue by GleipnirYmir** [RoyaleAPI/cr-api#452]
**Describe the bug**
When getting player info for GET https://api.royaleapi.com/player/#TAG the cards that are maxed from that player are not existing in the response.
Seems to be happenning from 18 December 2018.

**To Reproduce**
For example with (but works with whatever player has at least 1 maxed card):
GET https://api.royaleapi.com/player/P22PUCUL

**Expected behavior**
It is expected to have all the cards of that player regardless of it is MAXED or not.

**Screenshots**
Not applicable, seems an API problem.

**Desktop (please complete the following information):**
Not applicable, seems an API problem.

**Smartphone (please complete the following information):**
Not applicable, seems an API problem.

**Additional context**

**Comment by GleipnirYmir** [comment]
Seems I put a wrong tag. You could check with whatever player they have at least one maxed card. But now the initial problem seems fixed. Now the problem is that if the MAXED card is Rare, Epic or Legendary, no longer says `Maxed` on the `requiredForUpgrade` attribute. But that is related with the issue #451 for sure.

**Comment by selfish** [comment]
CAn't reproduce. I think this was fixed. Can you check @GleipnirYmir ?

**Comment by GleipnirYmir** [comment]
Yes, it is fixed. Thanks.
