### ISSUE TITLE
TOURNAMENT IDEA.

### ISSUE THREAD

**Issue by 1skinnypanda** [RoyaleAPI/cr-api#453]
### Idea/request:
  1. Briefly explain the idea or request.
  1. Briefly explain the rationale behind the request, or provide a use case.
  1. In which request/endpoint does this apply?
  1. Use the boxes at the bottom of this template to demonstrate a request and expected response.

### Issue Report:
  1. Did you encounter this recently, or has this bug always been there?
  1. Expected behaviour: 
  1. Console logs (if applicable): 
  1. Screenshots (if applicable):

### Request Details:

```
GET
https://api.royaleapi.com/top/clans
```

### Response Details:

```
Code: 200
[...]
```
I hope I'm doing this right.. anyway.

1. A tournament where all the cards are restored to thier vanilla stats.. their OP stats. 

1.personally I loved the old goblin gang.. so I'm pretty sure that others feel the same about other cards.

Examples include; the goblin gang is back to 6 units.. skeletons are back to 4 units..

**Comment by fourjr** [comment]
This feature request repository is meant for [RoyaleAPI](https://docs.royaleapi.com) and not Clash Royale in general. For in-game suggestions, you can post them [on reddit](https://clashroyale.reddit.com).
