### ISSUE TITLE
By default the cards menu put us to the levels tabs instead of summary ??

### ISSUE THREAD

**Issue by benwh4** [RoyaleAPI/cr-api#455]
### Issue Report:
  1. Did you encounter this recently, or has this bug always been there?
> no it wasn't like this before some month ago 
  1. Expected behaviour: 
> be linked to the summary of cards menu by default .

from the menu select the cards tabs and be linked to level by default
### Request Details:
```
GET
https://royaleapi.com/player/2P20LG9GQ/cards/levels
```
instead of

`https://royaleapi.com/player/2P20LG9GQ/cards/summary`

**Comment by selfish** [comment]
Hey, for issues with the site please log here:
https://github.com/RoyaleAPI/cr-api-ux/issues
