### ISSUE TITLE
Add war readiness menu for all member in the war submenu

### ISSUE THREAD

**Issue by benwh4** [RoyaleAPI/cr-api#456]
### Idea/request: add a war readiness tab in the clan menu
  1. I love the war readiness feature in the player profile page. I would love to have the same info (only the bar graph is ok) for all memeber of the clan as it would help leader to evaluate the probilities of winning the war.
  1. As clan leader, having a menu listing all the war readiness in the form of bar graphs would be nice.
  1. It would apply in the sub menu of war along current, log, analytics maybe another sub menu readiness which will gather all graph generated by the javascript in the player's profile.

**Comment by 6Sean** [comment]
@benwh4 This looks like a website request and you've posted it to the API issues page.  You may want to route it here: https://github.com/RoyaleAPI/cr-api-ux/issues

Apologies if I misread. 👍
