### ISSUE TITLE
Adding a war bonus T/F endpoint

### ISSUE THREAD

**Issue by TNAVRESSDOG** [RoyaleAPI/cr-api#458]
In the answer to the clan war log request, there is no way to tell if a member played there first battle but not there second if they have a bonus, or if they lost one and missed the second.  Because of this I am requesting that a ‘war bonus’ endpoint could be added as true or false. I see that this is in-acceptable information at the moment and if it is to stay that way, why?

**Comment by selfish** [comment]
Can't be done at the time.
It's in the plans for when it's possible.
