### ISSUE TITLE
Add war trophies in Clans Search

### ISSUE THREAD

**Issue by Dmitrygm1** [RoyaleAPI/cr-api#460]
Hi, when searching for a clan, I noticed that the only filters are the number of trophies and number of participants. This makes finding the clan you want not very easy, especially when there are a lot of other clans which carry the same name. An example of this is searching for the clan Inception- the clan doesn't have a trophy count that makes it stand out from all the other clans named Inception, but it has 3112 clan war trophies. The clan would have been easier to find had I also been able to specify the clan war trophies. Another change that would help find clans is having 2 sliders in the Clan trophies and (hopefully) Clan War trophies filter  (like in the Members filter), so that users could specify the approximate amount of trophies or clan war trophies the clan they are searching for has.
P.S. this is my first time here and I'm not a developer, so I apologize if I have the wrong format

**Comment by selfish** [comment]
Hey, is this issue regarding the website?
If so, it belongs here:
https://github.com/RoyaleAPI/cr-api-ux/issues
