### ISSUE TITLE
Add player last battle time

### ISSUE THREAD

**Issue by JFTellierTT** [RoyaleAPI/cr-api#462]
Feature request:
 -- Add the player last battle utctime to the player end point. --

Why it could be helpful:
-- It help clan leader to quickly see which player are active vs non-active. --

Can it be found elsewhere:
-- Yes it is in the players battle logs, but require the full scan, and this take forever when scanning all the 50 clan members, only for this information

Thanks you and keep the good work!

**Comment by PauloRamosGit** [comment]
I looked at https://api.clashroyale.com/v1/clans/#xxxxxx and they now have a memberList[x].lastSeen property. "lastSeen": "20190502T184413.000Z"
This should allow RoyaleAPI to get that information easily.

**Comment by selfish** [comment]
Added LastSeen in V3 API
