### ISSUE TITLE
V3 Open Issues

### ISSUE THREAD

**Issue by selfish** [RoyaleAPI/cr-api#463]
Issues:
- ~`https://v3-beta.royaleapi.com/clan/QPPPCYY/battles` returns `[]`~
- ~on the /players/ endpoint to specify which tag caused a 404~ (v128)

Feature-requests:
- Pagination
- ~multi-chests~  (v128)

**Comment by BlackHoleFox** [comment]
It seems like when you request a clan with /clan/tag/tracking and it isn't currently being tracked, it errors the server out instead of a 400 or other response. See response below.
```
{
  "error": true,
  "statusCode": 500,
  "statusText": "Cannot fetch clan tracking: pg: no rows in result set",
  "eventId": "6b38ec108566470e89dd6a589c0a3fa6",
  "info": "Additional information and support: http://discord.me/royaleapi"
}
```

**Comment by BlackHoleFox** [comment]
On the `/clan/<TAG>/history endpoint`, the players in the `members` array are missing the `lastSeen` field.
They exist in V2 and on most of the other responses that return `player` objects. See comparison with V2 below.
![image](https://user-images.githubusercontent.com/20936452/58757128-c34d7c80-84f5-11e9-8e74-f013759eb8ca.png)

**Comment by BlackHoleFox** [comment]
The `clanRank` and `rank` fields are still separate on the `/clan/history` and `/clan` endpoints, even though it was listed as becoming unified on `V82`. The most recent war history snapshots show this:
![image](https://user-images.githubusercontent.com/20936452/59234654-54e77900-8bdd-11e9-882a-b1bb4340c5a1.png)

**Comment by BlackHoleFox** [comment]
When using the `/clan/search` endpoint, any other query string except `name` returns a bad request error even though it matches the format shown in the V2 docs.
Ex: `https://v3-beta.royaleapi.com/clan/search?maxMembers=3` returns 
```{
  "error": true,
  "statusCode": 400,
  "statusText": "Failed to search clans: Failed to search clans: bad response: 400 Bad Request",
  "eventId": "8e28089d914e4479910f6e24a8209c56",
  "info": "Additional information and support: http://discord.me/royaleapi"
}
```
On a related note, all query strings in a request are ignored after name, such as `/clan/search?name=abcd&minMembers=35` returns clans with less then 5 members.
