### ISSUE TITLE
Broken info messages on /track

### ISSUE THREAD

**Issue by MrBartusek** [RoyaleAPI/cr-api#464]
### Issue Report:
When i request /track the message is broken for example, in bad tag the response contains "Fetch failed" 2 times 
**Fetch failed: Fetch failed:** illegal  characters in tag 'example' (allowed: 0289CGJLPQRUVY)",

### Request Details:

```
GET
https://v3-beta.royaleapi.com/clan/example/track
```

### Response Details for bad tag:

{
  "error": true,
  "statusCode": 400,
  "statusText": "**Fetch failed: Fetch failed:** illegal  characters in tag 'example' (allowed: 0289CGJLPQRUVY)",
  "eventId": "c8fe1efc93224ce1a04cdf35a98dc31d",
  "info": "Additional information and support: http://discord.me/royaleapi"
}

```
Code: 400
```
### Response Details for no tracking text in desc:

{
  "error": true,
  "statusCode": 417,
  "statusText": "**Tracking request failed: Tracking request failed:** clan should have 'royaleapi.com' in description",
  "info": "Additional information and support: http://discord.me/royaleapi"
}

```
Code: 417
```

**Comment by selfish** [comment]
Thanks for your report!

**Comment by selfish** [comment]
Fixed on v128, going live soon. (verify by accessing `/version` endpoint)
Thanks for the report!
