### ISSUE TITLE
warTrophies on history is always 0 

### ISSUE THREAD

**Issue by MrBartusek** [RoyaleAPI/cr-api#465]
### Request Details:

```
GET
https://v3-beta.royaleapi.com/clan/80LG2CPG/history
```

### Response Details:

```
Code: 200
Response on Pastebin cause it is too long https://pastebin.com/uZShPUmA
```
For now, I have no way to test this for other tags, if I will edit

**Comment by selfish** [comment]
Thanks for the report.
warTrophies isn't implemented in history.
History is expected to be rewritten and improved quite soon and it will be added!
