### ISSUE TITLE
% Cards level in war cvs

### ISSUE THREAD

**Issue by orlaf99** [RoyaleAPI/cr-api#467]
### Idea/request:
  1. add clan war readiness to war/analitics table and cvs
  1. this information is really important to choose players for the clan, actually it's quite difficult get this datas for each player and check their progress, putting this data into the cvs would save a lot of leaders time
  1. I think it would take too much space in the site so in spite of refused completely for graphical problems in the site it would be fantastic if added only to the cvs, you find in yellow the new columns
<img width="921" alt="Schermata 2019-08-17 alle 17 27 04" src="https://user-images.githubusercontent.com/54213175/63214143-c3ccdb00-c114-11e9-9993-f8cd3676793e.png">

**Comment by selfish** [comment]
I believe this belongs in royaleapi/cr-api-ux
@smlbiobot FYI
Closing for now.
@orlaf99 feel free to reopen there!
