### ISSUE TITLE
Gold chest name in player chest cycle

### ISSUE THREAD

**Issue by sondrewkk** [RoyaleAPI/cr-api#468]
### Issue Report:
  The golden chest name in the chests endopoint has changed from gold to golden in V3.
1. Noticed this 020919. First time I have seen this.
1. I expected same name as in V2, gold.

### Request Details:

To reproduce, make a request to https://api.royaleapi.com/player/tag/chests
```
GET
https://api.royaleapi.com/player/LL2Y89V9/chests
```

### Response Details:

```
Code: 200
{
    "upcoming": [
        "silver",
        "giant",
        "silver",
        "silver",
        "silver",
        "silver",
        "golden",
        "silver",
        "silver"
    ],
    "megaLightning": 68,
    "magical": 22,
    "legendary": 114,
    "epic": 685,
    "giant": 1
}
```

**Comment by selfish** [comment]
This is an intended change.
V3 does not meet V2 exactly, and the name was changed to adjust for the in-game name.
