### ISSUE TITLE
Multitag player battles for v3-api

### ISSUE THREAD

**Issue by marsigliadev** [RoyaleAPI/cr-api#473]
### Idea/request:
I want to make a request to implementation of multi-tag player battles. I'm talking about this endpoint:
``` 
https://api.royaleapi.com/player/<TAG>,<TAG>,<TAG>/battles
```

I've been using this endpoint on older versions but isn't implemented on v3. Thanks!

**Comment by selfish** [comment]
Implemented in v120, deploying now.
Thanks for your report!
