### ISSUE TITLE
Tower health left

### ISSUE THREAD

**Issue by sebov** [RoyaleAPI/cr-api#478]
### Idea/request:
Would it be possible to add **tower health left** (or even better King/Princess/Princess/Total tower health left) to the battles endpoint? The data is already available when viewing battles in a browser https://royaleapi.com/player/89JVRLCJ/battles

### Request Details:

```
GET
https://api.royaleapi.com/player/89JVRLCJ/battles
```

**Comment by marsigliadev** [comment]
Agreed

**Comment by MahdiBM** [comment]
I’m not really interested in tower damage as it almost shows nothing, but its easily accessible using the official api which makes me expect it to be available in royaleapi too.

**Comment by selfish** [comment]
Will ad in an upcoming release.

**Comment by selfish** [comment]
Implemented on v128, going live soon. (verify by accessing `/version` endpoint)
